### ISSUE TITLE
MBTiles output with Vector Tiles?

### ISSUE THREAD

**Issue by aberenyi** [mojodna/tilelive-http#16]
Hi there - I'd like to create an `.mbtiles` cache of vector tiles using [dirt](https://github.com/tobinbradley/dirt-simple-postgis-http-api) as an http source.

Dirt returns vector tiles with the following headers (amongst others):
```
Content-Type: application/x-protobuf
content-encoding: gzip
```

So I've tried
```
tilelive-copy http://dirtserver/mvt/v1/layer/{z}/{x}/{y} mbtiles:///path/to/cache.mbtiles
```

This works, however, it looks like that the output `.mbtiles` file does not have any format specified in the `metadata` table, and the the json definition of `vector_layers` is also missing - therefore the generated output cannot be used with e.g. [tileserver-gl] (https://github.com/klokantech/tileserver-gl) or `tessera`.

Is it possible to generate such an output?
If not - do you know any tool that makes this possible?

Cheers

**Comment by mojodna** [comment]
[`tl`](https://github.com/mojodna/tl) is an alternative to `tilelive-copy` that includes a `--info` parameter that allows TileJSON to be provided (in a file). That's where the format, `vector_layers`, and everything else can be provided.

`tl info mbtiles://./cache.mbtiles` will output the existing TileJSON, which you can use as the basis for the augmented version. (You can copy from one MBTiles archive to another and add the `--info` option to avoid re-downloading if you already have a full cache. There should probably be a way to edit TileJSON directly, triggered by `tl` (or something), but that doesn't exist yet.)

You can also edit the MBTiles archive directly using `sqlite3`, but that's more complicated.

(`tilelive-http` can't produce the relevant portions of the TileJSON that you're missing, as it doesn't see enough metadata without an upstream TileJSON endpoint.)

If dirt produces TileJSON, you can point to that in place of the URL template and metadata will be copied down appropriately.
