### ISSUE TITLE
Disambiguate between URL templates and TileJSON sources

### ISSUE THREAD

**Issue by sethfitz** [mojodna/tilelive-http#2]
[node-tilejson](https://github.com/mapbox/node-tilejson) should be used for TileJSON sources ([mojodna's fork](https://github.com/mojodna/node-tilejson/tree/integration) includes support for `tilejson+http:`, etc. protocols).

If prefixing the transport with `tilejson+` isn't preferable, this module can distinguish between a URL template and a TileJSON URL by assuming that non-templatized URLs (i.e. not containing `{z}`, `{x}`, `{y}`) will return TileJSON.

**Comment by elwino-cof** [comment]
I'm trying to use a Mapzen vector tiles source in my TM2 project.yml with Tessera (replacing mapbox streets vector tiles). Looks like the vector tiles are loaded properly from Mapzen server, but the raster images are empty. No error messages. Any tips or guidance would be appreciated.
